"""Vista minima del catalogo usata dall'agente (storie C3, B1, B3).

``onevisit_knowledge.Catalog`` (docs/contracts.md, sezione 1) soddisfa questi protocolli in
modo strutturale. L'agente dipende solo da qui, così i test usano un catalogo finto piccolo.
Gli attributi sono proprietà in sola lettura, quindi covarianti: un campo Pydantic ``str``
soddisfa una proprietà ``str | None``.
"""

from collections.abc import Mapping, Sequence
from datetime import date
from typing import Protocol


class SourceView(Protocol):
    """Fonte ufficiale salvata."""

    @property
    def id(self) -> str: ...
    @property
    def title(self) -> str: ...
    @property
    def url(self) -> str: ...
    @property
    def retrieved_at(self) -> date | None: ...


class QuestionView(Protocol):
    """Domanda che distingue le varianti di un servizio."""

    @property
    def id(self) -> str: ...
    @property
    def ask_it(self) -> str: ...
    @property
    def ask_en(self) -> str | None: ...
    @property
    def options(self) -> Sequence[str]: ...


class StepView(Protocol):
    """Passaggio presso un ente, in ordine."""

    @property
    def order(self) -> int: ...
    @property
    def ente(self) -> str | None: ...
    @property
    def text_it(self) -> str: ...
    @property
    def source_id(self) -> str: ...


class ServiceSummaryView(Protocol):
    """Riga dell'indice dei servizi."""

    @property
    def id(self) -> str: ...
    @property
    def title_it(self) -> str: ...
    @property
    def title_en(self) -> str | None: ...


class ServiceView(Protocol):
    """Servizio del catalogo (solo passaggi verificati)."""

    @property
    def id(self) -> str: ...
    @property
    def title_it(self) -> str: ...
    @property
    def title_en(self) -> str | None: ...
    @property
    def source_ids(self) -> Sequence[str]: ...
    @property
    def deciding_questions(self) -> Sequence[QuestionView]: ...
    @property
    def steps(self) -> Sequence[StepView]: ...
    @property
    def unknowns_it(self) -> Sequence[str]: ...


class ChecklistItemView(Protocol):
    """Requisito verificato della checklist."""

    @property
    def id(self) -> str: ...
    @property
    def text_it(self) -> str: ...
    @property
    def text_en(self) -> str | None: ...
    @property
    def source_id(self) -> str: ...
    @property
    def quote(self) -> str | None: ...
    @property
    def verified_at(self) -> date | None: ...
    @property
    def lead_time_days(self) -> int | None: ...


class ChecklistView(Protocol):
    """Checklist calcolata dalle risposte."""

    @property
    def service_id(self) -> str: ...
    @property
    def items(self) -> Sequence[ChecklistItemView]: ...
    @property
    def still_to_ask(self) -> Sequence[str]: ...
    @property
    def not_yet_verified(self) -> Sequence[str]: ...


class OfficeView(Protocol):
    """Sede anagrafica. Gli altri campi si leggono con ``model_dump`` se presente."""

    @property
    def id(self) -> str: ...
    @property
    def source_id(self) -> str: ...


class CatalogView(Protocol):
    """I metodi del catalogo che l'agente usa."""

    def services(self) -> Sequence[ServiceSummaryView]: ...
    def service(self, service_id: str) -> ServiceView | None: ...
    def checklist(self, service_id: str, answers: Mapping[str, str]) -> ChecklistView: ...
    def source(self, source_id: str) -> SourceView | None: ...
    def source_ids(self) -> frozenset[str]: ...
    def offices(
        self,
        *,
        area: str | None = None,
        municipio: int | None = None,
        lat: float | None = None,
        lon: float | None = None,
        limit: int = 3,
    ) -> Sequence[OfficeView]: ...
    def office(self, office_id: str) -> OfficeView | None: ...
    def is_stale(self, source_id: str, *, today: date, max_days: int) -> bool: ...
